services:
  #################################################################################################
  discovery-service:
    build: ./discovery-service/
    container_name: discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network
  #############################################################################################

  config-service:
    build: ./Configuration/config-service/
    container_name: config-service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  #############################################################################################

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
      - ./.docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: facturation
      POSTGRES_PASSWORD: facturation
      POSTGRES_DB: facturation
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "facturation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  #############################################################################################
  facture-service:
    build: ./facture-service
    container_name: facture-service
    volumes:
      - .:/var/www:cached
    ports:
      - "9090:80"
    environment:
      DISCOVERY_SERVICE_URL: http://discovery-service:8761/
      CONFIG_SERVER_URL: http://config-service:8888
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: facturation
      DB_USERNAME: facturation
      DB_PASSWORD: facturation
    depends_on:
      config-service:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - app-network
  #############################################################################################

  stock-service:
    build: ./stock-service/
    volumes:
      - ./stock-service:/app
    depends_on:
      - mongo-db
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/stock
    ports:
      - 4321:4321
    networks:
      - app-network
  #############################################################################################

  mongo-db:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  ####################################################################################################
  # Nginx
  ####################################################################################################
  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - .:/var/www
  #     - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - php

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  # db:
  #   image: mysql:8.1
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - .docker/db/data:/var/lib/mysql
  #     - .docker/logs:/var/log/mysql
  #     - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - .docker/db/sql:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: refactorian
  #     MYSQL_USER: refactorian
  #     MYSQL_PASSWORD: refactorian

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8080:80
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   volumes:
  #     - .docker/phpmyadmin/sessions:/sessions

  ####################################################################################################
  # Adminer
  ####################################################################################################
  # adminer:
  #   image: adminer
  #   ports:
  #     - 9090:8080
  #   depends_on:
  #     - db

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  # mail:
  #   image: axllent/mailpit:latest
  #   ports:
  #     - 8025:8025
  #     - 1025:1025

  ####################################################################################################
  # Redis
  ####################################################################################################
  # redis:
  #   image: redis:latest
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - .docker/redis/data:/data
  #   ports:
  #     - 6379:6379

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  # pgadmin:
  #     image: dpage/pgadmin4
  #     ports:
  #         - 5050:80
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #         - PGADMIN_DEFAULT_PASSWORD=password
  #     depends_on:
  #         - db
